name: my_eyes
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: 2.0.12
  cupertino_icons: 1.0.4
  mobx: 2.0.5
  flutter_modular: 3.4.1+1
  google_fonts: 2.1.0
  flutter_mobx: 2.0.2
  retrofit_generator: 2.0.1
  retrofit: 2.0.1
  json_serializable: 4.1.4
  dio: 4.0.3
  build_runner: 2.1.2
  slidy: 3.2.2+2
  fluttertoast: 8.0.7
  path_provider: ^2.0.8
  share_plus: ^3.0.4
  flutter_tts: ^3.3.3
  qr_code_scanner: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: 2.0.2
  modular_test: 1.0.1+1

flutter:
  uses-material-design: true

scripts:
  mobx: flutter pub run build_runner build --delete-conflicting-outputs
